server: 
   port: 8080
   
spring:
   kafka:
     consumer:
        bootstrap-servers: localhost:2181
        auto-offset-reset: earliest
        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value-deserializer: org.apache.kafka.common.serialization.JsonDeserializer
     producer:
        bootstrap-servers: localhost:2181
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
        value-serializer: org.apache.kafka.common.serialization.JsonSerializer